language: node_js
node_js: node
addons:
  chrome: stable
before_script:
  - npm run lint
script:
  # Read https://docs.travis-ci.com/user/chrome#Sandboxing
  - npm test -- --no-progress --no-watch --browsers ChromeHeadlessNoSandbox --code-coverage
  - npm run e2e -- --protractor-config protractor-ci.conf.js
after_success:
  - npx codecov
cache:
  directories:
    - $HOME/.npm
